### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ubergesundheit** [nuest/sensebox-binder#1]
I have two suggestions:

- Do not specify the `model` in the first data download section. The query now yields 417 
instead of 35 stations.
- Use 7 km for the radius arount the city center of Münster. There are now 16 stations with over 6000 measurements.

Otherwise looks good!

**Comment by nuest** [comment]
Thanks! Working on it now. Though I don't like this because my station does not hold the record anymore :-/
